### ISSUE TITLE
Build Package aborted due to missing items 

### ISSUE THREAD

**Issue by thomasliebenau** [vipm-io/vipm-desktop-issues#43]
I want to build a package with is related / uses NI Addons like NI FlexRIO.
When I try to build such a package VIPM aborts building  and reports missing VIs or Libraries.

VIPM reports such VIs in a very different path then LabVIEW 2023 64bit shows them in files view of Project Explorer (see highlighted entries in screenshot).

Build is only successful when  "Do Not Compile on Build (NotRrecommended)" is enabled

![VIPM Issue](https://github.com/vipm-io/vipm-desktop-issues/assets/25008402/bd74a4fc-c65e-45c1-8147-80b748b9d49f)

This happens with 
- LV 2023 Q3 64bit
- VIPM 2023.3 Free Edition

With best regards,
Thomas Liebenau

**Comment by thomasliebenau** [comment]
After installing the package build with enabled option "Do Not Compile on Build (NotRrecommended)" it has a bad palette

![bad palette](https://github.com/vipm-io/vipm-desktop-issues/assets/25008402/3d822e44-a901-43a9-b2f1-e14cc5f9f525)

in VIPM the palette is designed like this

![expected palette](https://github.com/vipm-io/vipm-desktop-issues/assets/25008402/4243c1e0-b1aa-4db9-9086-33d72230634d)

**Comment by jimkring** [comment]
Hi Thomas. Thank you for reporting this and providing updates on your testing/findings. I believe it’s an issue with the new LVAddons feature (install location of NI Packagess) in LabVIEW.

**Comment by jimkring** [comment]
Hi @thomasliebenau. This issue appears to impact package building in LabVIEW 2023 for packages with VIs calling toolkits installed under the `C:\Program Files\NI\LVAddons` location.  Starting in 2023 many NI toolkits (like DAQmx) install VIs in this location.  This will eventually be fixed in VIPM, but there is no ETA.

It should still be possible to build your package in an older version of LabVIEW (like 2020) if that's an option for you.

**Comment by jimkring** [comment]
@thomasliebenau I've filed a more detailed bug report here: #44

**Comment by jimkring** [comment]
Hi @thomasliebenau 

We will have a new build with a possible fix available for testing soon. It appears to fix the issue for simple cases of calling DAQmx in 2023. I can share a download link once it’s available, if you’re willing to test it.

Jim

**Comment by thomasliebenau** [comment]
Hi @jimkring 

I really like to support in testing.

Thomas

**Comment by jimkring** [comment]
Hi @thomasliebenau.

Great! Here is a link to beta build of VIPM 2024 Q1 f2 (build 2685):

- [vipm-24.1.2685-f2beta-windows-setup.exe.zip](https://jki.box.com/shared/static/hbmsw3my2xwwuamo3nx75l28t6bi679s.zip)

Thanks for your help testing this and please let us know how it works for building your package. It would be nice to close this issue :)

-Jim

**Comment by thomasliebenau** [comment]
Hi @jimkring,

I tested the beta within my project. Issue is not solved. Build is again aborted by missing items.

![image](https://github.com/vipm-io/vipm-desktop-issues/assets/25008402/6032ca36-ed85-43d2-9e0b-dc0dbccfd58f)

![image](https://github.com/vipm-io/vipm-desktop-issues/assets/25008402/7a86bdc6-5b01-4d43-8c56-b39cfb686571)


Thomas

**Comment by jimkring** [comment]
Hi @thomasliebenau. I saw a post flyby that seems to be gone now. it looked like there were some issues related to building packages that call FPGA add-ons.

**Comment by thomasliebenau** [comment]
Hi @jimkring,

I deleted the comment as I found some bad VI's in the folder to build a package from.
After solving this the beta is still not able to build a package that uses FPGA and FlexRio add-ons

![image](https://github.com/vipm-io/vipm-desktop-issues/assets/25008402/0e35364d-0ac3-4ff0-aedf-92a7f763bc04)

![image](https://github.com/vipm-io/vipm-desktop-issues/assets/25008402/3ef413b2-77ba-4682-9acd-f0dfcf7d47be)

Thomas

**Comment by jimkring** [comment]
@thomasliebenau OK, thanks for that extra info.  This gets a little bit trickier for FPGA VIs, due to how LabVIEW loads execution targets into memory and resolves symbolic paths with LVAddons. We'll have another test build you can try, soon.

**Comment by jimkring** [comment]
@thomasliebenau would you please try this new build: [vipm-24.1.2686-f2beta-windows-setup.exe.zip](https://jki.box.com/shared/static/2loles7p9bpwvid7wzhaess1lni92el6.zip)

Note: This should not show the missing items dialog, but it's not certain whether the full build will succeed -- that hasn't been tested yet with LabVIEW FPGA. We'll keep our fingers crossed...

**Comment by thomasliebenau** [comment]
Hi @jimkring,

I tested your new build right now. sorry to say it still aborts building because of missing files
![image](https://github.com/vipm-io/vipm-desktop-issues/assets/25008402/08b46f4c-bf1c-41db-a229-2cf5bba30899)

![image](https://github.com/vipm-io/vipm-desktop-issues/assets/25008402/7e6816ca-80cf-4910-8c73-935ebb26bce6)

**Comment by thomasliebenau** [comment]
If I try to build without compiling source files right ahead in a 2nd run vipm dies 

![image](https://github.com/vipm-io/vipm-desktop-issues/assets/25008402/7e6cc04c-c2dd-4c70-82ef-e47b152e08c8)

**Comment by jimkring** [comment]
Hi @thomasliebenau. Thanks for that info.

There's a test I'd like you to try, if you're willing.

Back up this file -- we're going to modify it and you'll want to restore the original.

`C:\Program Files\JKI\VI Package Manager\support\callbacks.llb\Check if File or Folder Exists [Multiple].vi`

Modify it's block diagram to force an output of `TRUE` for every file.

![image](https://github.com/vipm-io/vipm-desktop-issues/assets/381432/b3532d05-5ab4-41c9-9709-b3bc6bb3d775)

Then, try to build and see what happens.  It'll either work or you'll get a new type of error.

**Comment by jimkring** [comment]
@thomasliebenau could you also create a very small VI Package project (maybe a single VI in your package) that calls FlexRIO and produces errors during the build?  This will help us reproduce the issue on our end.
