### ISSUE TITLE
No installed packages listed in VIPM after upgrading LabVIEW 2025 Q1 to Q3

### ISSUE THREAD

**Issue by Michal-M-Kozak** [vipm-io/vipm-desktop-issues#83]
**Short Description of the Bug (in one or two sentences)**
After I upgraded LabVIEW 2025 Q1 to Q3, VIPM does not show almost any package as "Installed" (the exception is Workers - Debug Server, the only pakage with different icon in the first column). Newly installed package (after LabVIEW upgrade) is standardly listed as "Installed". 
Parallely to upgrade LabVIEW 2025, I probably upgraded more NI Toolkits and other SW including VIPM.

**Version Information**

VIPM Version and Build:
VIPM 2025.3 (build 2805)

Operating System Version:
Windows 11 Pro, 24H2

LabVIEW Version:
LabVIEW 2025 Q3 64-bit 25.3f0
(no problem with LabVIEW 2023 Q3 64-bit 23.3.6f6)

LabVIEW Bitness:
64-bit LabVIEW?

Virtualization or Processor Version Information
Intel i7, Dell notebook

**Steps To Reproduce**
1. Run VIPM
2. Choose LV version 2025 64-bit
3. Choose Installed

**Expected behavior**
There should be seen all (tens) installed packages.

**Actual Behavior**
There are not listed any packages installed before the upgrade of LabVIEW 2025 (except "Workers - Debug Server"), only installed after LabVIEW upgrade.

**Screenshots**

<img width="806" height="657" alt="Image" src="https://github.com/user-attachments/assets/e7aa1093-d133-4575-b9c7-9506cebdcf0e" />
Package "Workers - Debug Server" was installed before LabVIEW upgrade (so this is only one package behaves normally), package "Viewpoint TSVN Toolkit" was installed after LabVIEW upgrade (I am not sure, if it was there before or if it freash installation).
> 

**Anything else you'd like us to know?**
> Please add anything else you'd like us to know

**Comment by Tom-McQuillan** [comment]
Hi @Michal-M-Kozak Thanks for reporting this.
Update: I am able to reproduce the issue, and I have a strong theory of what is causing it. I will work with the team to create a plan of action.

**Comment by Tom-McQuillan** [comment]
Hi @Michal-M-Kozak ,
We have identified the root cause of the issue and have a plan of action to resolve it. We will have a patch for this in the upcoming weeks.

**Comment by Michal-M-Kozak** [comment]
Hi @Tom-McQuillan,
thank you for time for analysing the issue, is there any progress in solving this issue? I tried to reinstall VIPM and it did not helped. Is there any workaround, even just manually get list of installed packages?

**Comment by Tom-McQuillan** [comment]
The migration from LabVIEW Q1 to Q3 should be resolved in the latest release of VIPM (25Q3f1)

**Comment by Michal-M-Kozak** [comment]
Hi @Tom-McQuillan,
thank you for your message. Altough there is a progress after update, i.e. some packages are listed as installed (like AntiDoc, G CLI, my personal ones), there are plenty of them still not listed (as dependencies of listed ones or ones I installed for sure - all of them present in vi.lib) - DQMH, OpenG, Git API, MQTT, OpenURI etc.
There might be specific problem to the fact that I tried to resolve it myself, so I could break something, co reinstall might be needed. But if you are interested in deep dive to this issue, I will gladly provide additional information.
